// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdichzdkuuvixlqpsbrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkaWNoemRrdXV2aXhscXBzYnJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTg5NTIsImV4cCI6MjA2NTczNDk1Mn0.wQUPfv7hHhHjjZ5nsOkEPebwNExhThrstW8wIt7_DAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);